name: CI Build and Test

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test_build_ffmpeg_dev:
    name: Test build-ffmpeg_dev.yml
    uses: ./.github/workflows/build-ffmpeg_dev.yml
    permissions:
      contents: read
    with:
      repo_url: https://git.ffmpeg.org/gitweb/ffmpeg.git
      ffmpeg_branch: master
      test_seconds: "8"
      custom_env: ""
      create_release: false
    secrets: inherit

  test_build_ffmpeg_indocker_dev:
    name: Test build-ffmpeg_indocker_dev.yml
    uses: ./.github/workflows/build-ffmpeg_indocker_dev.yml
    permissions:
      contents: read
    with:
      repo_url: https://git.ffmpeg.org/gitweb/ffmpeg.git
      ffmpeg_branch: master
      test_seconds: "8"
      custom_env: ""
      create_release: false
    secrets: inherit
